name = "No Flesh Within Chest"
author = "YoruNina"
version = "1.0.0-DIM"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fbf3493374a0fdc4b3499fb12b40cc809b1b599aa653a135e9f09578e53caa2"

[versions]
forge = "43.3.5"
minecraft = "1.19.2"
